name: Format

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check clang-format version
        run: clang-format --version

      - name: Check clang-format configuration
        run: clang-format -style=file -dump-config

      - name: Check formatting
        run: make format-check
